name: CICD

on:
  push:

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Android APK (Release)
        run: ./gradlew :composeApp:assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/release/composeApp-release.apk
          if-no-files-found: error

  build_wasm:
    name: Build Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Wasm
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Upload Wasm Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: composeApp/build/dist/wasmJs/productionExecutable/
          if-no-files-found: error

      - name: Upload pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: composeApp/build/dist/wasmJs/productionExecutable/

  deploy_wasm:
    name: Deploy Wasm
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_wasm
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build_desktop:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            ext: msi
          - os: macos-latest
            ext: dmg
          - os: ubuntu-latest
            ext: deb
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Desktop Package
        run: ./gradlew :composeApp:packageDistributionForCurrentOS
        shell: bash

      - name: Upload Desktop Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kocoboy-${{ matrix.os }}.${{ matrix.ext }}
          path: composeApp/build/compose/binaries/main/${{ matrix.ext }}/*.${{ matrix.ext }}
          if-no-files-found: ignore

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ build_android, build_wasm, build_desktop ]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            android-apk/composeApp-release.apk
            wasm/**
            kocoboy-windows-latest.msi/*
            kocoboy-macos-latest.dmg/*
            kocoboy-ubuntu-latest.deb/*
